# Generated by Django 3.1.7 on 2021-02-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam_40', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='gamemode',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
