# Generated by Django 3.1.7 on 2021-03-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam_40', '0003_auto_20210228_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='subscore',
            field=models.FloatField(default=0),
        ),
    ]
