# Generated by Django 3.1.7 on 2021-03-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam_40', '0004_auto_20210301_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='salt',
            field=models.CharField(default='defau', max_length=6),
        ),
    ]
